name: Run basic tests

on: 
  push:
    branches:
      - "feature"

jobs:
  run_jest_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: npm 
      - run: npm test